/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zieln_com_myptrace_MainActivity */

#ifndef _Included_zieln_com_myptrace_MainActivity
#define _Included_zieln_com_myptrace_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zieln_com_myptrace_MainActivity
 * Method:    MyPtrace
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_zieln_com_myptrace_MainActivity_MyPtrace
  (JNIEnv *, jobject);

/*
 * Class:     zieln_com_myptrace_MainActivity
 * Method:    getChildPid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_zieln_com_myptrace_MainActivity_getChildPid
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
